# Generated by Django 5.1.5 on 2025-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardhi_backend', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('api_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
