# Generated by Django 5.1.5 on 2025-02-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardhi_backend', '0003_apiendpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='api_url',
            new_name='apiUrl',
        ),
    ]
