# Generated by Django 5.1.5 on 2025-02-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardhi_backend', '0004_rename_api_url_apiendpoint_apiurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='apiUrl',
            new_name='api_url',
        ),
    ]
