# Generated by Django 5.1.5 on 2025-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardhi_backend', '0006_input_cloud_provider_input_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.CharField(choices=[('API', 'API'), ('Model', 'Link to Model'), ('Dataset', 'Link to Dataset')], max_length=50),
        ),
    ]
