# Generated by Django 5.1.5 on 2025-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardhi_backend', '0007_alter_input_input_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='input',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='input',
            name='processed_data',
        ),
        migrations.RemoveField(
            model_name='input',
            name='signed_url',
        ),
    ]
